# Generated by Django 3.1.4 on 2021-01-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],), 'permissions': (('can_mark_returned', 'set book as returned'),)},
        ),
    ]
